FROM node:23-alpine
# Must be entire project because `prepare` script is run during `npm install` and requires all files.
COPY . /app
WORKDIR /app
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm run build

RUN apk add --no-cache git
RUN npm install -g pnpm
RUN pnpm install https://github.com/beamlit/supergateway
ENTRYPOINT ["npx","-y","@beamlit/supergateway","--port","80","--stdio"]